

export * from './all-interface';
export * from './area-interface';
export * from './birth-interface';
export * from './cards-interface';
export * from './competition-interface';
export * from './data-interface';
export * from './dribbles-interface';
export * from './duels-inetrface';
export * from './filter-interface';
export * from './fouls-interface';
export * from './games-inetrface';
export * from './goals-interface';
export * from './league-interface';
export * from './paging-interface';
export * from './parameters-interface';
export * from './passes-interface';
export * from './penalty-inetrface';
export * from './player-interface';
export * from './response-interface';
export * from './shots-inetrface';
export * from './standing-interface';
export * from './standings-interface';
export * from './statistic-inetrface';
export * from './substitutes-interface';
export * from './tackles-interface';
export * from './team-interface';
export * from './top-scorer-interface';
